SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = 'sqlite:///websync.db'
SECRET_KEY = "websync"
JWT_SECRET_KEY = "websync"
JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS = ['access']
CORS_HEADERS = 'Content-Type'
